My commit

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,15 +1,24 @@
 #!/usr/bin/env bash
-# This script transfers a file from the client to a server using scp.
-# Check if correct number of parameters is provided
-if [ $# -lt 3 ];
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-    exit;
-fi;
+# This script transfers a file from a client to a server using scp.
 
-if [ $# -ge 4 ];
-then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+# Check if correct number of parameters is provided
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+# Transfer file using scp with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~/
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File successfully transferred to $username@$server_ip:~/"
 else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-fi;
+    echo "Error: File transfer failed."
+fi
